export const GET_PRICING_DATA = 'GET_PRICING_DATA';
export const GET_PARTNERS_DATA = 'GET_PARTNERS_DATA';
export const GET_SOCIAL_DATA = 'GET_SOCIAL_DATA'; 
export const LANGUAGE = 'LANGUAGE';
export const GET_SERVICES_DATA = 'GET_SERVICES_DATA'